# contracts.py
from typing import Protocol

class EngineServices(Protocol):
    def emit_alert(self, msg: str) -> None: ...
    # add more as you truly need them later:
    # def send_image(self, path: str, caption: str | None = None) -> None: ...
    # def schedule_job(self, name: str, delay_sec: int, payload: dict) -> None: ...
